# .goreleaser.yml
# Configuration for GoReleaser
# https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: redup

before:
  hooks:
    # You may remove this if you don't use go modules
    - go mod tidy

builds:
  -
    # Main build
    id: redup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/dakoctba/redup/cmd.version={{.Version}} -X github.com/dakoctba/redup/cmd.buildTime={{.Date}} -X github.com/dakoctba/redup/cmd.gitCommit={{.Commit}}
    main: ./
    binary: redup

archives:
  -
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Archive settings
    id: redup
    files:
      - LICENSE
      - README.md

    # Default format is tar.gz
    formats: [tar.gz]

    # Use zip for macOS and Windows
    format_overrides:
      - goos: darwin
        formats: [zip]
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: dakoctba
    name: redup
  draft: false  # Publicação automática
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  mode: replace
  # Configurar para garantir que os binários sejam publicados
  ids:
    - redup

# Explicitly define what to publish
# Include source code and built binaries
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}'

# Skip the upload for snapshots
snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: redup
    homepage: "https://github.com/dakoctba/redup"
    description: "Duplicate File Manager - A CLI tool to find and manage duplicate files by content"
    repository:
      name: homebrew-tap
      owner: dakoctba
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    test: |
      system "#{bin}/redup", "--version"
    install: |
      bin.install "redup"
